import type { FoodCatalogSource, FoodPortionOption } from "@workspace/db";

export interface CuratedGlobalFoodSearchItem {
  id: string;
  source: FoodCatalogSource | "member_custom";
  sourceProductId?: string;
  catalogItemId?: string;
  memberFoodItemId?: string;
  barcode?: string;
  name: string;
  brand?: string;
  servingLabel: string;
  servingGrams?: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar?: number;
  sodiumMg?: number;
  ingredients: string[];
  allergens: string[];
  portionOptions: FoodPortionOption[];
  confidence: "high" | "medium" | "low";
  provenance: {
    provider: string;
    cached: boolean;
    qualityScore?: number;
  };
}

interface CuratedFoodDefinition {
  id: string;
  name: string;
  cuisine: string;
  category: string;
  servingLabel: string;
  servingGrams: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  aliases: string[];
  ingredients: string[];
  allergens: string[];
  portionOptions: FoodPortionOption[];
  healthyTags: string[];
  popularity: number;
}

const STOP_WORDS = new Set(["a", "an", "and", "by", "for", "of", "the", "with"]);

const SYNONYM_GROUPS = [
  ["tea", "chai", "chaai", "chay", "masala tea", "milk tea"],
  ["coffee", "espresso", "cappuccino", "capuccino", "latte", "frappe", "frape", "cold coffee"],
  ["curd", "dahi", "yogurt", "yoghurt"],
  ["roti", "chapati", "phulka", "fulka"],
  ["biryani", "biriyani", "briyani", "briyani rice"],
  ["paneer", "panir", "cottage cheese"],
  ["chickpea", "chickpeas", "chana", "chole", "choley"],
  ["lentil", "lentils", "dal", "daal", "dhal"],
  ["dosa", "dosai", "dhosa"],
  ["idli", "idly"],
  ["noodle", "noodles", "chow mein", "hakka"],
  ["momo", "momos", "dumpling", "dumplings", "dim sum"],
  ["pizza", "piza"],
  ["pasta", "spaghetti", "penne", "macaroni"],
  ["burger", "hamburger", "cheeseburger"],
  ["fries", "french fries", "chips"],
  ["oats", "oatmeal", "porridge"],
  ["protein", "whey", "protein shake", "smoothie"],
  ["salad", "greens", "lettuce"],
  ["wrap", "roll", "shawarma", "burrito"],
];

const SYNONYM_TOKEN_MAP = new Map<string, Set<string>>();

for (const group of SYNONYM_GROUPS) {
  const expanded = new Set(group.flatMap((entry) => tokenize(entry)));
  for (const entry of group) {
    for (const token of tokenize(entry)) {
      const existing = SYNONYM_TOKEN_MAP.get(token) ?? new Set<string>();
      expanded.forEach((expandedToken) => existing.add(expandedToken));
      SYNONYM_TOKEN_MAP.set(token, existing);
    }
  }
}

function f(
  id: string,
  name: string,
  cuisine: string,
  category: string,
  servingLabel: string,
  servingGrams: number,
  calories: number,
  protein: number,
  carbs: number,
  fat: number,
  fiber: number,
  aliases: string[],
  ingredients: string[],
  options: {
    allergens?: string[];
    portions?: FoodPortionOption[];
    healthyTags?: string[];
    popularity?: number;
  } = {},
): CuratedFoodDefinition {
  return {
    id,
    name,
    cuisine,
    category,
    servingLabel,
    servingGrams,
    calories,
    protein,
    carbs,
    fat,
    fiber,
    aliases,
    ingredients,
    allergens: options.allergens ?? [],
    portionOptions: options.portions ?? [],
    healthyTags: options.healthyTags ?? [],
    popularity: options.popularity ?? 50,
  };
}

const CURATED_GLOBAL_FOODS: CuratedFoodDefinition[] = [
  f(
    "roti",
    "Roti / Chapati",
    "Indian",
    "Breads",
    "1 medium roti",
    40,
    120,
    3.5,
    22,
    3,
    3,
    ["phulka", "fulka", "wheat roti", "chapati"],
    ["whole wheat flour", "water"],
    {
      allergens: ["wheat"],
      popularity: 100,
      portions: [
        { label: "1 phulka", grams: 30, aliases: ["phulka"] },
        { label: "1 medium roti", grams: 40, aliases: ["roti", "chapati"] },
        { label: "1 large roti", grams: 55 },
      ],
    },
  ),
  f(
    "naan",
    "Naan",
    "Indian",
    "Breads",
    "1 naan",
    90,
    260,
    7,
    45,
    6,
    2,
    ["butter naan", "plain naan", "tandoori naan"],
    ["refined wheat flour", "yogurt", "oil"],
    { allergens: ["wheat", "milk"], popularity: 88 },
  ),
  f(
    "paratha",
    "Plain Paratha",
    "Indian",
    "Breads",
    "1 paratha",
    80,
    250,
    6,
    34,
    10,
    4,
    ["parantha", "tawa paratha", "laccha paratha"],
    ["whole wheat flour", "oil"],
    { allergens: ["wheat"], popularity: 86 },
  ),
  f(
    "steamed-rice",
    "Steamed Rice",
    "Indian",
    "Rice",
    "1 katori",
    150,
    195,
    4,
    43,
    0.4,
    1,
    ["white rice", "chawal", "plain rice", "bhat"],
    ["rice"],
    { popularity: 96 },
  ),
  f(
    "brown-rice",
    "Brown Rice",
    "Global",
    "Healthy Grains",
    "1 bowl",
    180,
    200,
    5,
    42,
    1.8,
    3.5,
    ["healthy rice", "whole grain rice"],
    ["brown rice"],
    { healthyTags: ["high fiber"], popularity: 75 },
  ),
  f(
    "jeera-rice",
    "Jeera Rice",
    "Indian",
    "Rice",
    "1 plate",
    180,
    260,
    5,
    48,
    7,
    1.5,
    ["cumin rice"],
    ["rice", "cumin", "ghee"],
    { allergens: ["milk"], popularity: 78 },
  ),
  f(
    "dal-tadka",
    "Dal Tadka",
    "Indian",
    "Dal & Legumes",
    "1 katori",
    150,
    180,
    9,
    22,
    6,
    6,
    ["daal tadka", "lentil curry", "yellow dal", "dhal"],
    ["lentils", "spices", "oil"],
    {
      popularity: 98,
      portions: [
        { label: "1 small katori", grams: 120, aliases: ["small bowl"] },
        { label: "1 katori", grams: 150, aliases: ["bowl"] },
        { label: "1 large bowl", grams: 220 },
      ],
    },
  ),
  f(
    "rajma",
    "Rajma Masala",
    "Indian",
    "Dal & Legumes",
    "1 katori",
    170,
    235,
    11,
    35,
    6,
    10,
    ["kidney bean curry", "rajma chawal"],
    ["kidney beans", "tomato", "spices"],
    { popularity: 90 },
  ),
  f(
    "chole",
    "Chole Masala",
    "Indian",
    "Dal & Legumes",
    "1 katori",
    170,
    250,
    12,
    34,
    8,
    9,
    ["chana masala", "chickpea curry", "choley"],
    ["chickpeas", "tomato", "spices"],
    { popularity: 90 },
  ),
  f(
    "khichdi",
    "Moong Dal Khichdi",
    "Indian",
    "Rice",
    "1 bowl",
    220,
    280,
    11,
    48,
    5,
    6,
    ["khichri", "khichadi", "dal rice"],
    ["rice", "moong dal", "ghee"],
    { allergens: ["milk"], healthyTags: ["comfort food"], popularity: 82 },
  ),
  f(
    "paneer-bhurji",
    "Paneer Bhurji",
    "Indian",
    "Paneer",
    "1 katori",
    150,
    310,
    18,
    9,
    23,
    2,
    ["panir bhurji", "cottage cheese bhurji"],
    ["paneer", "onion", "tomato", "spices", "oil"],
    { allergens: ["milk"], popularity: 88 },
  ),
  f(
    "paneer-tikka",
    "Paneer Tikka",
    "Indian",
    "Paneer",
    "6 pieces",
    160,
    340,
    22,
    12,
    24,
    2,
    ["panir tikka", "grilled paneer"],
    ["paneer", "yogurt", "spices"],
    { allergens: ["milk"], popularity: 86 },
  ),
  f(
    "palak-paneer",
    "Palak Paneer",
    "Indian",
    "Paneer",
    "1 katori",
    180,
    320,
    17,
    13,
    23,
    5,
    ["saag paneer", "spinach paneer"],
    ["paneer", "spinach", "cream"],
    { allergens: ["milk"], popularity: 84 },
  ),
  f(
    "butter-chicken",
    "Butter Chicken",
    "Indian",
    "Chicken",
    "1 katori",
    180,
    430,
    28,
    12,
    30,
    2,
    ["murgh makhani", "chicken makhani"],
    ["chicken", "tomato", "butter", "cream"],
    { allergens: ["milk"], popularity: 92 },
  ),
  f(
    "chicken-curry",
    "Chicken Curry",
    "Indian",
    "Chicken",
    "1 katori",
    180,
    310,
    30,
    8,
    18,
    2,
    ["homestyle chicken", "chicken masala"],
    ["chicken", "onion", "tomato", "spices"],
    { popularity: 92 },
  ),
  f(
    "tandoori-chicken",
    "Tandoori Chicken",
    "Indian",
    "Chicken",
    "2 pieces",
    180,
    330,
    42,
    5,
    16,
    1,
    ["grilled chicken tikka", "tangdi"],
    ["chicken", "yogurt", "spices"],
    { allergens: ["milk"], healthyTags: ["high protein"], popularity: 88 },
  ),
  f(
    "chicken-biryani",
    "Chicken Biryani",
    "Indian",
    "Rice",
    "1 plate",
    300,
    520,
    28,
    62,
    18,
    4,
    ["biriyani", "briyani", "hyderabadi biryani", "dum biryani"],
    ["rice", "chicken", "spices", "oil"],
    { popularity: 96 },
  ),
  f(
    "veg-biryani",
    "Vegetable Biryani",
    "Indian",
    "Rice",
    "1 plate",
    300,
    430,
    10,
    72,
    12,
    6,
    ["veg biriyani", "briyani", "pulao"],
    ["rice", "vegetables", "spices", "oil"],
    { popularity: 84 },
  ),
  f(
    "egg-curry",
    "Egg Curry",
    "Indian",
    "Eggs",
    "2 eggs with gravy",
    180,
    260,
    15,
    10,
    18,
    2,
    ["anda curry", "egg masala"],
    ["egg", "onion", "tomato", "spices"],
    { allergens: ["egg"], popularity: 82 },
  ),
  f(
    "fish-curry",
    "Fish Curry",
    "Indian",
    "Fish & Seafood",
    "1 katori",
    180,
    280,
    32,
    8,
    13,
    2,
    ["machli curry", "meen curry"],
    ["fish", "coconut", "spices"],
    { allergens: ["fish"], popularity: 78 },
  ),
  f(
    "dosa",
    "Plain Dosa",
    "South Indian",
    "Breakfast",
    "1 dosa",
    120,
    180,
    4,
    32,
    4,
    2,
    ["dosai", "dhosa", "sada dosa"],
    ["rice", "urad dal"],
    { popularity: 92 },
  ),
  f(
    "masala-dosa",
    "Masala Dosa",
    "South Indian",
    "Breakfast",
    "1 dosa",
    220,
    360,
    8,
    58,
    10,
    5,
    ["mysore masala dosa", "dhosa"],
    ["rice", "urad dal", "potato"],
    { popularity: 90 },
  ),
  f(
    "idli",
    "Idli",
    "South Indian",
    "Breakfast",
    "2 idlis",
    100,
    130,
    4,
    26,
    1,
    2,
    ["idly", "steamed idli"],
    ["rice", "urad dal"],
    { healthyTags: ["steamed"], popularity: 90 },
  ),
  f(
    "poha",
    "Poha",
    "Indian",
    "Breakfast",
    "1 bowl",
    180,
    260,
    6,
    46,
    7,
    4,
    ["flattened rice", "kanda poha"],
    ["flattened rice", "peanuts", "spices"],
    { allergens: ["peanut"], popularity: 86 },
  ),
  f(
    "upma",
    "Upma",
    "South Indian",
    "Breakfast",
    "1 bowl",
    180,
    280,
    7,
    46,
    8,
    4,
    ["rava upma", "sooji upma"],
    ["semolina", "vegetables"],
    { allergens: ["wheat"], popularity: 82 },
  ),
  f(
    "samosa",
    "Samosa",
    "Indian",
    "Snacks",
    "1 samosa",
    100,
    260,
    5,
    32,
    13,
    3,
    ["samosa chaat"],
    ["refined wheat flour", "potato", "oil"],
    { allergens: ["wheat"], popularity: 84 },
  ),
  f(
    "dhokla",
    "Dhokla",
    "Indian",
    "Snacks",
    "4 pieces",
    120,
    180,
    7,
    30,
    4,
    4,
    ["khaman", "khaman dhokla"],
    ["gram flour", "spices"],
    { healthyTags: ["steamed"], popularity: 78 },
  ),
  f(
    "pav-bhaji",
    "Pav Bhaji",
    "Indian",
    "Street Food",
    "1 plate",
    300,
    450,
    12,
    68,
    16,
    8,
    ["paav bhaji"],
    ["bread", "potato", "vegetables", "butter"],
    { allergens: ["wheat", "milk"], popularity: 86 },
  ),
  f(
    "curd",
    "Curd / Dahi",
    "Indian",
    "Dairy",
    "1 bowl",
    150,
    95,
    5,
    7,
    5,
    0,
    ["yogurt", "yoghurt", "plain curd"],
    ["milk"],
    { allergens: ["milk"], healthyTags: ["probiotic"], popularity: 86 },
  ),
  f(
    "raita",
    "Raita",
    "Indian",
    "Dairy",
    "1 katori",
    150,
    110,
    5,
    10,
    5,
    1,
    ["boondi raita", "cucumber raita"],
    ["curd", "vegetables", "spices"],
    { allergens: ["milk"], popularity: 76 },
  ),
  f(
    "masala-chai",
    "Masala Chai",
    "Indian",
    "Beverages",
    "1 cup",
    180,
    120,
    4,
    18,
    4,
    0,
    ["chai", "tea", "milk tea", "masala tea", "chaai", "chay"],
    ["milk", "tea", "sugar", "spices"],
    { allergens: ["milk"], popularity: 100 },
  ),
  f(
    "lassi",
    "Sweet Lassi",
    "Indian",
    "Beverages",
    "1 glass",
    250,
    230,
    8,
    36,
    6,
    0,
    ["lassi", "yogurt drink"],
    ["curd", "sugar"],
    { allergens: ["milk"], popularity: 78 },
  ),
  f(
    "sprouts-chaat",
    "Sprouts Chaat",
    "Indian",
    "Healthy Snacks",
    "1 bowl",
    180,
    210,
    14,
    34,
    3,
    9,
    ["moong sprouts", "healthy chaat"],
    ["sprouts", "onion", "tomato", "lemon"],
    { healthyTags: ["high protein", "high fiber"], popularity: 76 },
  ),
  f(
    "aloo-gobi",
    "Aloo Gobi",
    "Indian",
    "Vegetables",
    "1 katori",
    180,
    210,
    5,
    28,
    9,
    6,
    ["potato cauliflower sabzi"],
    ["potato", "cauliflower", "spices"],
    { popularity: 74 },
  ),
  f(
    "mango",
    "Mango",
    "Global",
    "Fruits",
    "1 medium mango",
    200,
    135,
    1.5,
    35,
    0.6,
    3,
    ["aam", "alphonso mango"],
    ["mango"],
    { healthyTags: ["fruit"], popularity: 86 },
  ),
  f(
    "banana",
    "Banana",
    "Global",
    "Fruits",
    "1 medium banana",
    118,
    105,
    1.3,
    27,
    0.3,
    3,
    ["kela", "elaichi banana"],
    ["banana"],
    { healthyTags: ["fruit"], popularity: 88 },
  ),
  f(
    "whey-shake",
    "Whey Protein Shake",
    "Global",
    "Fitness",
    "1 scoop with water",
    35,
    130,
    25,
    3,
    2,
    0,
    ["protein shake", "whey", "gym protein"],
    ["whey protein"],
    { allergens: ["milk"], healthyTags: ["high protein"], popularity: 82 },
  ),
  f(
    "oats-porridge",
    "Oats Porridge",
    "Global",
    "Healthy Breakfast",
    "1 bowl",
    220,
    260,
    10,
    42,
    6,
    7,
    ["oatmeal", "oats", "masala oats"],
    ["oats", "milk"],
    { allergens: ["milk"], healthyTags: ["high fiber"], popularity: 84 },
  ),

  f(
    "veg-fried-rice",
    "Vegetable Fried Rice",
    "Chinese",
    "Rice",
    "1 plate",
    280,
    420,
    10,
    64,
    13,
    5,
    ["chinese fried rice", "fried rice"],
    ["rice", "vegetables", "soy sauce"],
    { allergens: ["soy"], popularity: 84 },
  ),
  f(
    "chicken-fried-rice",
    "Chicken Fried Rice",
    "Chinese",
    "Rice",
    "1 plate",
    300,
    520,
    26,
    62,
    18,
    4,
    ["chinese chicken rice"],
    ["rice", "chicken", "egg", "soy sauce"],
    { allergens: ["egg", "soy"], popularity: 84 },
  ),
  f(
    "hakka-noodles",
    "Hakka Noodles",
    "Indo-Chinese",
    "Noodles",
    "1 plate",
    280,
    470,
    12,
    72,
    14,
    5,
    ["chow mein", "veg noodles", "chinese noodles"],
    ["noodles", "vegetables", "soy sauce"],
    { allergens: ["wheat", "soy"], popularity: 88 },
  ),
  f(
    "chilli-chicken",
    "Chilli Chicken",
    "Indo-Chinese",
    "Chicken",
    "1 plate",
    250,
    430,
    32,
    24,
    22,
    3,
    ["chili chicken", "dry chilli chicken"],
    ["chicken", "capsicum", "soy sauce"],
    { allergens: ["soy"], popularity: 82 },
  ),
  f(
    "gobi-manchurian",
    "Gobi Manchurian",
    "Indo-Chinese",
    "Snacks",
    "1 plate",
    250,
    380,
    8,
    48,
    17,
    6,
    ["cauliflower manchurian"],
    ["cauliflower", "cornflour", "soy sauce"],
    { allergens: ["soy", "wheat"], popularity: 82 },
  ),
  f(
    "chicken-manchurian",
    "Chicken Manchurian",
    "Indo-Chinese",
    "Chicken",
    "1 plate",
    250,
    450,
    30,
    28,
    24,
    2,
    ["manchurian chicken"],
    ["chicken", "soy sauce", "cornflour"],
    { allergens: ["soy", "wheat"], popularity: 78 },
  ),
  f(
    "momos",
    "Momos / Dumplings",
    "Tibetan-Chinese",
    "Snacks",
    "6 pieces",
    180,
    290,
    12,
    42,
    8,
    3,
    ["momo", "dumpling", "dim sum", "dimsum"],
    ["wheat wrapper", "vegetables"],
    { allergens: ["wheat"], popularity: 86 },
  ),
  f(
    "spring-roll",
    "Spring Roll",
    "Chinese",
    "Snacks",
    "2 rolls",
    160,
    330,
    8,
    42,
    14,
    4,
    ["veg spring rolls"],
    ["wheat wrapper", "vegetables", "oil"],
    { allergens: ["wheat"], popularity: 72 },
  ),
  f(
    "hot-sour-soup",
    "Hot and Sour Soup",
    "Chinese",
    "Soups",
    "1 bowl",
    250,
    120,
    6,
    18,
    3,
    2,
    ["hot sour soup"],
    ["vegetables", "soy sauce", "vinegar"],
    { allergens: ["soy"], popularity: 70 },
  ),
  f(
    "kung-pao-chicken",
    "Kung Pao Chicken",
    "Chinese",
    "Chicken",
    "1 bowl",
    250,
    430,
    35,
    22,
    24,
    4,
    ["kung pao", "peanut chicken"],
    ["chicken", "peanuts", "chilli"],
    { allergens: ["peanut", "soy"], popularity: 68 },
  ),
  f(
    "tofu-stir-fry",
    "Tofu Stir Fry",
    "Chinese",
    "Healthy Protein",
    "1 bowl",
    240,
    320,
    24,
    22,
    17,
    6,
    ["stir fried tofu", "tofu vegetables"],
    ["tofu", "vegetables", "soy sauce"],
    { allergens: ["soy"], healthyTags: ["plant protein"], popularity: 70 },
  ),

  f(
    "pad-thai",
    "Pad Thai",
    "Thai",
    "Noodles",
    "1 plate",
    300,
    550,
    22,
    76,
    18,
    4,
    ["thai noodles"],
    ["rice noodles", "peanuts", "tamarind"],
    { allergens: ["peanut", "egg"], popularity: 78 },
  ),
  f(
    "thai-green-curry",
    "Thai Green Curry",
    "Thai",
    "Curry",
    "1 bowl",
    250,
    360,
    18,
    18,
    25,
    4,
    ["green curry", "thai curry"],
    ["coconut milk", "green curry paste", "vegetables"],
    { popularity: 80 },
  ),
  f(
    "thai-red-curry",
    "Thai Red Curry",
    "Thai",
    "Curry",
    "1 bowl",
    250,
    380,
    20,
    20,
    26,
    4,
    ["red curry", "thai curry"],
    ["coconut milk", "red curry paste"],
    { popularity: 76 },
  ),
  f(
    "tom-yum",
    "Tom Yum Soup",
    "Thai",
    "Soups",
    "1 bowl",
    300,
    160,
    18,
    14,
    5,
    2,
    ["tom yum", "thai soup"],
    ["lemongrass", "mushroom", "prawns"],
    { allergens: ["shellfish"], popularity: 68 },
  ),
  f(
    "thai-basil-chicken",
    "Thai Basil Chicken",
    "Thai",
    "Chicken",
    "1 bowl",
    230,
    360,
    32,
    14,
    20,
    3,
    ["pad kra pao", "basil chicken"],
    ["chicken", "basil", "chilli"],
    { popularity: 70 },
  ),
  f(
    "papaya-salad",
    "Som Tam Papaya Salad",
    "Thai",
    "Salads",
    "1 plate",
    220,
    180,
    5,
    32,
    5,
    6,
    ["som tam", "green papaya salad"],
    ["papaya", "lime", "peanuts"],
    { allergens: ["peanut"], healthyTags: ["salad"], popularity: 64 },
  ),
  f(
    "jasmine-rice",
    "Jasmine Rice",
    "Thai",
    "Rice",
    "1 bowl",
    180,
    235,
    4,
    52,
    0.5,
    1,
    ["thai rice"],
    ["jasmine rice"],
    { popularity: 62 },
  ),
  f(
    "mango-sticky-rice",
    "Mango Sticky Rice",
    "Thai",
    "Desserts",
    "1 plate",
    250,
    420,
    5,
    80,
    10,
    3,
    ["thai mango rice"],
    ["sticky rice", "mango", "coconut milk"],
    { popularity: 62 },
  ),

  f(
    "margherita-pizza",
    "Margherita Pizza",
    "Italian",
    "Pizza",
    "2 slices",
    180,
    450,
    18,
    58,
    16,
    3,
    ["cheese pizza", "pizza"],
    ["wheat crust", "tomato", "cheese"],
    { allergens: ["wheat", "milk"], popularity: 90 },
  ),
  f(
    "veggie-pizza",
    "Vegetable Pizza",
    "Italian",
    "Pizza",
    "2 slices",
    190,
    430,
    16,
    60,
    14,
    5,
    ["veg pizza", "pizza"],
    ["wheat crust", "vegetables", "cheese"],
    { allergens: ["wheat", "milk"], popularity: 84 },
  ),
  f(
    "arrabbiata-pasta",
    "Pasta Arrabbiata",
    "Italian",
    "Pasta",
    "1 plate",
    280,
    430,
    14,
    76,
    8,
    5,
    ["red sauce pasta", "penne arrabbiata"],
    ["pasta", "tomato", "olive oil"],
    { allergens: ["wheat"], popularity: 82 },
  ),
  f(
    "alfredo-pasta",
    "Pasta Alfredo",
    "Italian",
    "Pasta",
    "1 plate",
    300,
    620,
    18,
    72,
    28,
    4,
    ["white sauce pasta", "cream pasta"],
    ["pasta", "cream", "cheese"],
    { allergens: ["wheat", "milk"], popularity: 82 },
  ),
  f(
    "spaghetti-bolognese",
    "Spaghetti Bolognese",
    "Italian",
    "Pasta",
    "1 plate",
    320,
    560,
    28,
    74,
    18,
    5,
    ["meat pasta", "spaghetti"],
    ["spaghetti", "meat sauce"],
    { allergens: ["wheat"], popularity: 74 },
  ),
  f(
    "lasagna",
    "Lasagna",
    "Italian",
    "Pasta",
    "1 slice",
    260,
    430,
    24,
    38,
    22,
    3,
    ["lasagne"],
    ["pasta sheets", "cheese", "tomato"],
    { allergens: ["wheat", "milk"], popularity: 70 },
  ),
  f(
    "risotto",
    "Mushroom Risotto",
    "Italian",
    "Rice",
    "1 bowl",
    280,
    420,
    12,
    58,
    15,
    3,
    ["risotto"],
    ["rice", "mushroom", "cheese"],
    { allergens: ["milk"], popularity: 66 },
  ),
  f(
    "garlic-bread",
    "Garlic Bread",
    "Italian",
    "Sides",
    "2 pieces",
    90,
    260,
    6,
    34,
    10,
    2,
    ["cheese garlic bread"],
    ["bread", "garlic", "butter"],
    { allergens: ["wheat", "milk"], popularity: 78 },
  ),
  f(
    "croissant",
    "Croissant",
    "French",
    "Bakery",
    "1 croissant",
    65,
    270,
    5,
    30,
    14,
    2,
    ["butter croissant", "plain croissant", "crossaint", "croisant"],
    ["wheat flour", "butter"],
    { allergens: ["wheat", "milk"], popularity: 72 },
  ),
  f(
    "caprese-salad",
    "Caprese Salad",
    "Italian",
    "Salads",
    "1 plate",
    180,
    260,
    13,
    8,
    20,
    2,
    ["tomato mozzarella salad"],
    ["tomato", "mozzarella", "basil"],
    { allergens: ["milk"], healthyTags: ["salad"], popularity: 58 },
  ),
  f(
    "minestrone",
    "Minestrone Soup",
    "Italian",
    "Soups",
    "1 bowl",
    300,
    180,
    8,
    30,
    4,
    8,
    ["vegetable soup"],
    ["beans", "vegetables", "pasta"],
    { allergens: ["wheat"], healthyTags: ["high fiber"], popularity: 58 },
  ),
  f(
    "tiramisu",
    "Tiramisu",
    "Italian",
    "Desserts",
    "1 slice",
    120,
    360,
    6,
    42,
    18,
    1,
    ["coffee dessert"],
    ["mascarpone", "coffee", "ladyfingers"],
    { allergens: ["milk", "egg", "wheat"], popularity: 68 },
  ),

  f(
    "burger",
    "Burger",
    "American",
    "Fast Food",
    "1 burger",
    220,
    520,
    24,
    48,
    28,
    3,
    ["hamburger", "veg burger", "chicken burger"],
    ["bun", "patty", "sauce"],
    { allergens: ["wheat"], popularity: 88 },
  ),
  f(
    "cheeseburger",
    "Cheeseburger",
    "American",
    "Fast Food",
    "1 burger",
    230,
    580,
    30,
    45,
    34,
    3,
    ["cheese burger"],
    ["bun", "beef patty", "cheese"],
    { allergens: ["wheat", "milk"], popularity: 78 },
  ),
  f(
    "french-fries",
    "French Fries",
    "American",
    "Fast Food",
    "1 medium serving",
    120,
    365,
    4,
    48,
    17,
    4,
    ["fries", "potato fries", "chips"],
    ["potato", "oil", "salt"],
    { popularity: 86 },
  ),
  f(
    "grilled-chicken-breast",
    "Grilled Chicken Breast",
    "American",
    "Healthy Protein",
    "1 breast",
    160,
    260,
    48,
    0,
    6,
    0,
    ["lean chicken", "chicken breast"],
    ["chicken"],
    { healthyTags: ["high protein"], popularity: 82 },
  ),
  f(
    "club-sandwich",
    "Club Sandwich",
    "American",
    "Sandwiches",
    "1 sandwich",
    250,
    520,
    28,
    52,
    22,
    5,
    ["chicken sandwich", "sandwich"],
    ["bread", "chicken", "egg", "vegetables"],
    { allergens: ["wheat", "egg"], popularity: 76 },
  ),
  f(
    "pancakes",
    "Pancakes",
    "American",
    "Breakfast",
    "3 pancakes",
    220,
    520,
    12,
    82,
    16,
    3,
    ["pancake"],
    ["flour", "milk", "egg", "syrup"],
    { allergens: ["wheat", "milk", "egg"], popularity: 72 },
  ),
  f(
    "waffles",
    "Waffles",
    "American",
    "Breakfast",
    "2 waffles",
    180,
    430,
    10,
    58,
    18,
    2,
    ["waffle"],
    ["flour", "milk", "egg"],
    { allergens: ["wheat", "milk", "egg"], popularity: 68 },
  ),
  f(
    "scrambled-eggs",
    "Scrambled Eggs",
    "Global",
    "Eggs",
    "2 eggs",
    120,
    210,
    14,
    2,
    16,
    0,
    ["anda bhurji western", "eggs"],
    ["egg", "butter"],
    { allergens: ["egg", "milk"], popularity: 80 },
  ),
  f(
    "omelette",
    "Omelette",
    "Global",
    "Eggs",
    "2 egg omelette",
    140,
    230,
    16,
    4,
    17,
    1,
    ["omelet", "masala omelette"],
    ["egg", "vegetables"],
    { allergens: ["egg"], popularity: 82 },
  ),
  f(
    "caesar-salad",
    "Caesar Salad",
    "American",
    "Salads",
    "1 bowl",
    250,
    330,
    18,
    18,
    22,
    5,
    ["chicken caesar salad"],
    ["lettuce", "chicken", "dressing"],
    { allergens: ["milk", "fish"], healthyTags: ["salad"], popularity: 66 },
  ),
  f(
    "mac-cheese",
    "Mac and Cheese",
    "American",
    "Pasta",
    "1 bowl",
    250,
    550,
    20,
    60,
    26,
    3,
    ["macaroni cheese"],
    ["pasta", "cheese", "milk"],
    { allergens: ["wheat", "milk"], popularity: 66 },
  ),
  f(
    "steak",
    "Steak",
    "American",
    "Meat",
    "1 steak",
    220,
    560,
    52,
    0,
    38,
    0,
    ["beef steak"],
    ["beef"],
    { popularity: 54 },
  ),

  f(
    "burrito",
    "Burrito",
    "Mexican",
    "Wraps",
    "1 burrito",
    320,
    650,
    28,
    82,
    24,
    12,
    ["bean burrito", "wrap"],
    ["tortilla", "beans", "rice"],
    { allergens: ["wheat"], popularity: 70 },
  ),
  f(
    "tacos",
    "Tacos",
    "Mexican",
    "Fast Food",
    "2 tacos",
    200,
    420,
    22,
    38,
    22,
    6,
    ["taco"],
    ["tortilla", "beans", "salsa"],
    { popularity: 68 },
  ),
  f(
    "quesadilla",
    "Quesadilla",
    "Mexican",
    "Fast Food",
    "1 quesadilla",
    220,
    540,
    24,
    48,
    28,
    4,
    ["cheese quesadilla"],
    ["tortilla", "cheese"],
    { allergens: ["wheat", "milk"], popularity: 62 },
  ),
  f(
    "hummus",
    "Hummus",
    "Middle Eastern",
    "Healthy Dips",
    "1 small bowl",
    100,
    240,
    8,
    20,
    15,
    6,
    ["chickpea dip"],
    ["chickpeas", "tahini", "olive oil"],
    { allergens: ["sesame"], healthyTags: ["plant protein"], popularity: 66 },
  ),
  f(
    "falafel",
    "Falafel",
    "Middle Eastern",
    "Healthy Snacks",
    "4 pieces",
    120,
    330,
    13,
    32,
    18,
    8,
    ["chickpea balls"],
    ["chickpeas", "herbs", "oil"],
    { healthyTags: ["plant protein"], popularity: 64 },
  ),
  f(
    "shawarma",
    "Chicken Shawarma",
    "Middle Eastern",
    "Wraps",
    "1 wrap",
    260,
    560,
    34,
    48,
    24,
    4,
    ["chicken roll", "shawarma roll"],
    ["flatbread", "chicken", "garlic sauce"],
    { allergens: ["wheat", "sesame"], popularity: 72 },
  ),
  f(
    "pita",
    "Pita Bread",
    "Middle Eastern",
    "Breads",
    "1 pita",
    60,
    165,
    6,
    33,
    1,
    2,
    ["khubz", "flatbread"],
    ["wheat flour"],
    { allergens: ["wheat"], popularity: 54 },
  ),

  f(
    "quinoa-bowl",
    "Quinoa Bowl",
    "Global",
    "Healthy Bowls",
    "1 bowl",
    300,
    420,
    16,
    58,
    14,
    10,
    ["healthy bowl", "protein bowl"],
    ["quinoa", "vegetables", "beans"],
    { healthyTags: ["high fiber"], popularity: 72 },
  ),
  f(
    "tofu-bowl",
    "Tofu Rice Bowl",
    "Global",
    "Healthy Bowls",
    "1 bowl",
    320,
    480,
    26,
    62,
    15,
    8,
    ["tofu bowl", "plant protein bowl"],
    ["tofu", "rice", "vegetables"],
    { allergens: ["soy"], healthyTags: ["plant protein"], popularity: 68 },
  ),
  f(
    "tempeh",
    "Tempeh",
    "Global",
    "Healthy Protein",
    "100g",
    100,
    195,
    20,
    8,
    11,
    5,
    ["fermented soy protein"],
    ["soybeans"],
    { allergens: ["soy"], healthyTags: ["plant protein"], popularity: 48 },
  ),
  f(
    "lentil-soup",
    "Lentil Soup",
    "Global",
    "Soups",
    "1 bowl",
    300,
    240,
    15,
    38,
    4,
    11,
    ["dal soup", "healthy soup"],
    ["lentils", "vegetables"],
    { healthyTags: ["high fiber"], popularity: 70 },
  ),
  f(
    "chickpea-salad",
    "Chickpea Salad",
    "Global",
    "Salads",
    "1 bowl",
    250,
    350,
    14,
    48,
    12,
    12,
    ["chana salad", "protein salad"],
    ["chickpeas", "vegetables", "olive oil"],
    { healthyTags: ["high fiber"], popularity: 68 },
  ),
  f(
    "sweet-potato",
    "Sweet Potato",
    "Global",
    "Healthy Carbs",
    "1 medium",
    150,
    135,
    2,
    31,
    0.2,
    5,
    ["shakarkandi", "roasted sweet potato"],
    ["sweet potato"],
    { healthyTags: ["complex carbs"], popularity: 66 },
  ),
  f(
    "broccoli",
    "Broccoli",
    "Global",
    "Vegetables",
    "1 cup",
    150,
    50,
    4,
    10,
    0.5,
    5,
    ["steamed broccoli"],
    ["broccoli"],
    { healthyTags: ["vegetable"], popularity: 58 },
  ),
  f(
    "mixed-salad",
    "Mixed Vegetable Salad",
    "Global",
    "Salads",
    "1 bowl",
    200,
    120,
    4,
    18,
    5,
    6,
    ["green salad", "healthy salad"],
    ["lettuce", "cucumber", "tomato"],
    { healthyTags: ["salad"], popularity: 70 },
  ),
  f(
    "grilled-fish",
    "Grilled Fish",
    "Global",
    "Fish & Seafood",
    "1 fillet",
    180,
    260,
    38,
    0,
    11,
    0,
    ["fish fillet", "healthy fish"],
    ["fish"],
    { allergens: ["fish"], healthyTags: ["high protein"], popularity: 64 },
  ),
  f(
    "salmon",
    "Salmon",
    "Global",
    "Fish & Seafood",
    "1 fillet",
    160,
    330,
    34,
    0,
    20,
    0,
    ["grilled salmon"],
    ["salmon"],
    { allergens: ["fish"], healthyTags: ["omega 3"], popularity: 58 },
  ),
  f(
    "tuna-salad",
    "Tuna Salad",
    "Global",
    "Salads",
    "1 bowl",
    220,
    330,
    32,
    12,
    16,
    4,
    ["tuna bowl"],
    ["tuna", "vegetables", "dressing"],
    { allergens: ["fish"], healthyTags: ["high protein"], popularity: 56 },
  ),
  f(
    "chia-pudding",
    "Chia Pudding",
    "Global",
    "Healthy Breakfast",
    "1 cup",
    180,
    280,
    9,
    28,
    15,
    12,
    ["chia seed pudding"],
    ["chia seeds", "milk"],
    { allergens: ["milk"], healthyTags: ["high fiber"], popularity: 62 },
  ),
  f(
    "greek-yogurt",
    "Greek Yogurt Parfait",
    "Global",
    "Healthy Breakfast",
    "1 cup",
    200,
    260,
    20,
    30,
    6,
    4,
    ["greek yoghurt", "yogurt parfait"],
    ["greek yogurt", "fruit", "granola"],
    { allergens: ["milk"], healthyTags: ["high protein"], popularity: 68 },
  ),
  f(
    "smoothie-bowl",
    "Smoothie Bowl",
    "Global",
    "Healthy Breakfast",
    "1 bowl",
    300,
    420,
    12,
    72,
    10,
    9,
    ["fruit smoothie bowl", "acai bowl"],
    ["fruit", "yogurt", "granola"],
    { allergens: ["milk"], healthyTags: ["fruit"], popularity: 66 },
  ),
  f(
    "avocado-toast",
    "Avocado Toast",
    "Global",
    "Healthy Breakfast",
    "1 toast",
    160,
    300,
    9,
    32,
    16,
    8,
    ["avo toast"],
    ["bread", "avocado"],
    { allergens: ["wheat"], healthyTags: ["healthy fats"], popularity: 64 },
  ),
  f(
    "boiled-eggs",
    "Boiled Eggs",
    "Global",
    "Eggs",
    "2 eggs",
    100,
    155,
    13,
    1,
    11,
    0,
    ["hard boiled eggs", "anda"],
    ["egg"],
    { allergens: ["egg"], healthyTags: ["high protein"], popularity: 84 },
  ),
  f(
    "peanut-butter-toast",
    "Peanut Butter Toast",
    "Global",
    "Breakfast",
    "1 toast",
    90,
    280,
    10,
    28,
    15,
    4,
    ["pb toast"],
    ["bread", "peanut butter"],
    { allergens: ["wheat", "peanut"], popularity: 58 },
  ),
  f(
    "protein-smoothie",
    "Protein Smoothie",
    "Global",
    "Fitness",
    "1 glass",
    350,
    360,
    30,
    42,
    8,
    5,
    ["protein shake", "banana protein shake"],
    ["milk", "banana", "whey"],
    { allergens: ["milk"], healthyTags: ["high protein"], popularity: 74 },
  ),

  f(
    "green-tea",
    "Green Tea",
    "Global",
    "Beverages",
    "1 cup",
    240,
    2,
    0,
    0,
    0,
    0,
    ["tea", "green chai", "unsweetened tea"],
    ["green tea"],
    { healthyTags: ["low calorie"], popularity: 78 },
  ),
  f(
    "black-tea",
    "Black Tea",
    "Global",
    "Beverages",
    "1 cup",
    240,
    2,
    0,
    0,
    0,
    0,
    ["tea", "plain tea", "chai without milk"],
    ["black tea"],
    { healthyTags: ["low calorie"], popularity: 70 },
  ),
  f(
    "lemon-tea",
    "Lemon Tea",
    "Global",
    "Beverages",
    "1 cup",
    240,
    45,
    0,
    12,
    0,
    0,
    ["tea", "nimbu chai"],
    ["tea", "lemon", "sugar"],
    { popularity: 60 },
  ),
  f(
    "coffee",
    "Coffee",
    "Global",
    "Beverages",
    "1 cup",
    240,
    5,
    0,
    0,
    0,
    0,
    ["black coffee", "americano", "kaapi"],
    ["coffee"],
    { healthyTags: ["low calorie"], popularity: 90 },
  ),
  f(
    "espresso",
    "Espresso",
    "Global",
    "Beverages",
    "1 shot",
    30,
    3,
    0,
    0,
    0,
    0,
    ["coffee shot"],
    ["coffee"],
    { popularity: 62 },
  ),
  f(
    "cappuccino",
    "Cappuccino",
    "Global",
    "Beverages",
    "1 cup",
    180,
    120,
    6,
    12,
    5,
    0,
    ["capuccino", "coffee", "milk coffee"],
    ["coffee", "milk"],
    { allergens: ["milk"], popularity: 76 },
  ),
  f(
    "latte",
    "Latte",
    "Global",
    "Beverages",
    "1 cup",
    240,
    160,
    8,
    16,
    7,
    0,
    ["cafe latte", "coffee", "milk coffee"],
    ["coffee", "milk"],
    { allergens: ["milk"], popularity: 72 },
  ),
  f(
    "cold-coffee",
    "Cold Coffee",
    "Global",
    "Beverages",
    "1 glass",
    300,
    260,
    8,
    38,
    8,
    0,
    ["iced coffee", "coffee shake"],
    ["milk", "coffee", "sugar"],
    { allergens: ["milk"], popularity: 78 },
  ),
  f(
    "frappe",
    "Frappe",
    "Global",
    "Beverages",
    "1 glass",
    350,
    420,
    8,
    62,
    16,
    0,
    ["frape", "frappuccino", "coffee", "cold coffee"],
    ["milk", "coffee", "sugar", "cream"],
    { allergens: ["milk"], popularity: 70 },
  ),
  f(
    "coconut-water",
    "Coconut Water",
    "Global",
    "Beverages",
    "1 glass",
    250,
    45,
    1,
    11,
    0,
    0,
    ["nariyal pani"],
    ["coconut water"],
    { healthyTags: ["hydration"], popularity: 74 },
  ),

  f(
    "sushi",
    "Sushi",
    "Japanese",
    "Rice",
    "6 pieces",
    180,
    300,
    16,
    48,
    5,
    2,
    ["maki", "nigiri"],
    ["rice", "fish", "seaweed"],
    { allergens: ["fish"], popularity: 60 },
  ),
  f(
    "ramen",
    "Ramen",
    "Japanese",
    "Noodles",
    "1 bowl",
    500,
    560,
    24,
    72,
    20,
    5,
    ["noodle soup"],
    ["noodles", "broth", "egg"],
    { allergens: ["wheat", "egg", "soy"], popularity: 62 },
  ),
  f(
    "pho",
    "Pho",
    "Vietnamese",
    "Soups",
    "1 bowl",
    500,
    430,
    28,
    62,
    8,
    4,
    ["vietnamese noodle soup"],
    ["rice noodles", "broth", "meat"],
    { popularity: 50 },
  ),
  f(
    "bibimbap",
    "Bibimbap",
    "Korean",
    "Rice",
    "1 bowl",
    450,
    560,
    24,
    78,
    16,
    8,
    ["korean rice bowl"],
    ["rice", "vegetables", "egg"],
    { allergens: ["egg", "soy"], popularity: 52 },
  ),
  f(
    "kimchi",
    "Kimchi",
    "Korean",
    "Sides",
    "1 serving",
    100,
    30,
    2,
    6,
    0.5,
    3,
    ["fermented cabbage"],
    ["cabbage", "chilli"],
    { healthyTags: ["fermented"], popularity: 46 },
  ),
];

function normalizeSearchText(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function tokenize(value: string) {
  const normalized = normalizeSearchText(value);
  if (!normalized) return [];
  return normalized
    .split(" ")
    .map((token) => token.trim())
    .filter((token) => token && !STOP_WORDS.has(token));
}

function expandedQueryTokens(query: string) {
  const tokens = new Set(tokenize(query));
  for (const token of [...tokens]) {
    const synonyms = SYNONYM_TOKEN_MAP.get(token);
    if (synonyms) synonyms.forEach((synonym) => tokens.add(synonym));
  }
  return tokens;
}

function searchableText(food: CuratedFoodDefinition) {
  return [
    food.name,
    food.cuisine,
    food.category,
    ...food.aliases,
    ...food.ingredients,
    ...food.healthyTags,
    ...food.portionOptions.flatMap((portion) => [portion.label, ...(portion.aliases ?? [])]),
  ].join(" ");
}

function levenshteinDistance(left: string, right: string) {
  if (left === right) return 0;
  if (!left.length) return right.length;
  if (!right.length) return left.length;

  let previous = Array.from({ length: right.length + 1 }, (_value, index) => index);
  for (let leftIndex = 0; leftIndex < left.length; leftIndex += 1) {
    const current = [leftIndex + 1];
    for (let rightIndex = 0; rightIndex < right.length; rightIndex += 1) {
      const substitutionCost = left[leftIndex] === right[rightIndex] ? 0 : 1;
      current[rightIndex + 1] = Math.min(
        current[rightIndex] + 1,
        previous[rightIndex + 1] + 1,
        previous[rightIndex] + substitutionCost,
      );
    }
    previous = current;
  }
  return previous[right.length] ?? Math.max(left.length, right.length);
}

function diceCoefficient(left: string, right: string) {
  if (left === right) return 1;
  if (left.length < 2 || right.length < 2) return 0;
  const bigrams = new Map<string, number>();
  for (let index = 0; index < left.length - 1; index += 1) {
    const bigram = left.slice(index, index + 2);
    bigrams.set(bigram, (bigrams.get(bigram) ?? 0) + 1);
  }
  let overlap = 0;
  for (let index = 0; index < right.length - 1; index += 1) {
    const bigram = right.slice(index, index + 2);
    const count = bigrams.get(bigram) ?? 0;
    if (count > 0) {
      bigrams.set(bigram, count - 1);
      overlap += 1;
    }
  }
  return (2 * overlap) / (left.length + right.length - 2);
}

function tokenMatchScore(queryToken: string, candidateTokens: Set<string>) {
  if (candidateTokens.has(queryToken)) return 18;
  let bestScore = 0;
  for (const candidateToken of candidateTokens) {
    if (queryToken.length >= 3 && candidateToken.startsWith(queryToken))
      bestScore = Math.max(bestScore, 13);
    if (candidateToken.length >= 4 && queryToken.startsWith(candidateToken))
      bestScore = Math.max(bestScore, 10);
    const typoLimit = queryToken.length <= 5 ? 1 : 2;
    if (levenshteinDistance(queryToken, candidateToken) <= typoLimit)
      bestScore = Math.max(bestScore, 11);
    if (diceCoefficient(queryToken, candidateToken) >= 0.72) bestScore = Math.max(bestScore, 8);
  }
  return bestScore;
}

function scoreFood(food: CuratedFoodDefinition, rawQuery: string) {
  const query = normalizeSearchText(rawQuery);
  if (!query) return food.popularity / 10;

  const normalizedName = normalizeSearchText(food.name);
  const normalizedAliases = food.aliases.map(normalizeSearchText);
  const normalizedSearchText = normalizeSearchText(searchableText(food));
  const candidateTokens = new Set(tokenize(normalizedSearchText));
  const queryTokens = tokenize(query);
  const expandedTokens = expandedQueryTokens(query);

  let score = 0;
  if (normalizedName === query) score += 120;
  if (normalizedAliases.includes(query)) score += 110;
  if (normalizedName.includes(query)) score += 75;
  if (normalizedSearchText.includes(query)) score += 45;

  for (const token of queryTokens) {
    score += tokenMatchScore(token, candidateTokens);
  }

  for (const token of expandedTokens) {
    if (!queryTokens.includes(token) && candidateTokens.has(token)) score += 8;
  }

  if (normalizeSearchText(food.cuisine) === query || normalizeSearchText(food.category) === query) {
    score += 35;
  }

  return score + food.popularity / 20;
}

function defaultPortionOptions(food: CuratedFoodDefinition): FoodPortionOption[] {
  if (food.portionOptions.length) return food.portionOptions;
  const aliases = [food.name, ...food.aliases].slice(0, 8);
  return [
    { label: food.servingLabel, grams: food.servingGrams, aliases },
    ...(food.servingGrams === 100 ? [] : [{ label: "100g", grams: 100 }]),
  ];
}

function toSearchItem(food: CuratedFoodDefinition): CuratedGlobalFoodSearchItem {
  return {
    id: `curated-${food.id}`,
    source: "curated",
    sourceProductId: `curated-${food.id}`,
    name: food.name,
    servingLabel: food.servingLabel,
    servingGrams: food.servingGrams,
    calories: food.calories,
    protein: food.protein,
    carbs: food.carbs,
    fat: food.fat,
    fiber: food.fiber,
    ingredients: food.ingredients,
    allergens: food.allergens,
    portionOptions: defaultPortionOptions(food),
    confidence: "medium",
    provenance: {
      provider: "curated-global-food-search",
      cached: true,
      qualityScore: Math.min(88, 45 + Math.round(food.popularity / 2)),
    },
  };
}

export function searchCuratedGlobalFoods(
  query: string,
  limit: number,
): CuratedGlobalFoodSearchItem[] {
  const safeLimit = Math.max(1, Math.min(50, Math.round(limit)));
  if (!normalizeSearchText(query)) {
    return [...CURATED_GLOBAL_FOODS]
      .sort((left, right) => right.popularity - left.popularity)
      .slice(0, safeLimit)
      .map(toSearchItem);
  }

  return CURATED_GLOBAL_FOODS.map((food) => ({ food, score: scoreFood(food, query) }))
    .filter((candidate) => candidate.score >= 12)
    .sort((left, right) => right.score - left.score || right.food.popularity - left.food.popularity)
    .slice(0, safeLimit)
    .map((candidate) => toSearchItem(candidate.food));
}

export function getCuratedGlobalFoodCount() {
  return CURATED_GLOBAL_FOODS.length;
}
